Repository woowacourse-teams/2021-nolto, pull requests merged in 2021-11, with the labels that each got.

#691 [FE] refactor: 주석 제거
  frontend/src/components/CommentModule/@common/Comment/Comment.tsx
  frontend/src/components/Searchbar/Searchbar.tsx
  frontend/src/contexts/member/MemberProvider.tsx
  frontend/src/hooks/queries/comment/useCommentWrite.ts
  frontend/src/hooks/useTheme.ts
  frontend/src/pages/FeedDetail/FeedDetailContent/FeedDetailContent.tsx
  frontend/src/pages/SearchResult/SearchResultHeader/SearchResultHeader.tsx
  frontend/src/utils/CustomError.ts
  frontend/src/utils/HttpError.ts
Labels: 🔨 refactor, 🌈 frontend

#692 docs: 기술 스택, 인프라, CI/CD 아키텍처 추가
  README.md
  img/ci_cd.jpg
  img/infra.jpg
  img/tech.png
Labels: 📖 documentation

#699 docs: infra 구조 수정
  README.md
  img/infra.jpg
Labels: 📖 documentation, 🚀 backend

#701 docs: 수정 이전 버전 인프라 구조 명시
  README.md
  img/before_infra.png
Labels: 📖 documentation, 🚀 backend
